name: cantwait28
description: A Flutter project that counts days down to exciting dates in the future.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  cloud_firestore: ^4.9.2

  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  intl: ^0.18.0
  bloc: ^8.1.2
  firebase_core: ^2.16.0
  flutterfire_ui: ^0.4.0
  firebase_auth: ^4.10.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
